# Generated by Django 4.0 on 2023-01-04 13:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=255)),
                ('middlename', models.TextField(blank=True, max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('username', models.TextField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('address_1', models.TextField(max_length=255)),
                ('address_2', models.TextField(blank=True, max_length=255)),
                ('country', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='users')),
                ('password', models.TextField(default='', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('baseprice', models.TextField(max_length=255)),
                ('finalprice', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('saledate', models.DateTimeField()),
                ('saletime', models.TimeField(default='12:00:00')),
                ('description', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('thumbnailimage', models.ImageField(default='', upload_to='product/thumbnail')),
                ('status', models.CharField(choices=[('idle', 'idle'), ('sold', 'sold'), ('bought', 'bought'), ('auction', 'auction')], default='idle', max_length=9)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main_app.product')),
            ],
        ),
    ]
