# Generated by Django 4.0 on 2022-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
