# Generated by Django 4.0 on 2022-12-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_address_2_alter_user_middlename'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('baseprice', models.TextField(max_length=255)),
                ('finalprice', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saledate', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('idle', 'idle'), ('sold', 'sold'), ('bought', 'bought'), ('auction', 'auction')], default='idle', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main_app.product')),
            ],
        ),
    ]
