# Generated by Django 4.1.7 on 2023-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_image1_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', upload_to='product/image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='product/image2'),
        ),
    ]
