# Generated by Django 4.1.7 on 2023-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_image1_alter_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='police_verified',
            field=models.BooleanField(default=False),
        ),
    ]
