# Generated by Django 4.0 on 2022-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.DeleteModel(
            name='product_image',
        ),
    ]
